# Generated by Django 2.2.24 on 2022-03-15 17:09

import django.db.models.deletion
import opaque_keys.edx.django.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CourseBlock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_id', models.CharField(max_length=255, unique=True)),
                ('block_type', models.CharField(max_length=255)),
                ('course_id', opaque_keys.edx.django.models.CourseKeyField(db_index=True, max_length=255)),
            ],
            options={
                'verbose_name': 'Course Block',
            },
        ),
        migrations.CreateModel(
            name='CourseBlockData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_type', models.CharField(max_length=255)),
                ('data', models.TextField()),
                ('course_block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meta_translations.CourseBlock')),
            ],
            options={
                'verbose_name': 'Course Block Data',
                'unique_together': {('course_block', 'data_type')},
            },
        ),
        migrations.CreateModel(
            name='WikiTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('translation', models.TextField(blank=True, null=True)),
                ('sent', models.BooleanField(default=False)),
                ('applied', models.BooleanField(default=False)),
                ('overwrite', models.BooleanField(default=False)),
                ('last_fetched', models.DateTimeField(blank=True, null=True)),
                ('source_block_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meta_translations.CourseBlockData')),
                ('target_block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meta_translations.CourseBlock')),
            ],
            options={
                'verbose_name': 'Wiki Meta Translations',
                'unique_together': {('target_block', 'source_block_data')},
            },
        ),
    ]
