# Generated by Django 2.2.24 on 2022-03-16 12:39

import opaque_keys.edx.django.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meta_translations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', opaque_keys.edx.django.models.CourseKeyField(db_index=True, max_length=255)),
                ('base_course_id', opaque_keys.edx.django.models.CourseKeyField(db_index=True, max_length=255)),
            ],
            options={
                'verbose_name': 'Course Translation',
                'unique_together': {('course_id', 'base_course_id')},
            },
        ),
    ]
