# Generated by Django 2.2.24 on 2022-04-08 06:35

import django.db.models.deletion
import jsonfield.encoder
import jsonfield.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('meta_translations', '0002_coursetranslation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wikitranslation',
            name='overwrite',
        ),
        migrations.RemoveField(
            model_name='wikitranslation',
            name='sent',
        ),
        migrations.AddField(
            model_name='courseblock',
            name='direction_flag',
            field=models.CharField(blank=True, choices=[('D', 'Destination'), ('S', 'Source')], max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='courseblock',
            name='lang',
            field=jsonfield.fields.JSONField(default='[]', dump_kwargs={'cls': jsonfield.encoder.JSONEncoder, 'separators': (',', ':')}, load_kwargs={}),
        ),
        migrations.AddField(
            model_name='courseblockdata',
            name='content_updated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='courseblockdata',
            name='mapping_updated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='wikitranslation',
            name='approved_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='wikitranslation',
            name='revision',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
