# Generated by Django 2.2.24 on 2022-04-11 08:59

import opaque_keys.edx.django.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meta_translations', '0003_auto_20220408_0635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseblock',
            name='block_id',
            field=opaque_keys.edx.django.models.UsageKeyField(db_index=True, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='courseblock',
            name='direction_flag',
            field=models.CharField(blank=True, choices=[('D', 'Destination'), ('S', 'Source')], default='S', max_length=2, null=True),
        ),
    ]
