# Generated by Django 2.2.24 on 2022-04-15 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meta_translations', '0004_auto_20220411_0859'),
    ]

    operations = [
        migrations.AddField(
            model_name='wikitranslation',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
