# Generated by Django 2.2.24 on 2022-05-20 08:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meta_translations', '0006_courseblockdata_parsed_keys'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wikitranslation',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
