# Generated by Django 2.2.24 on 2022-05-20 11:17

import jsonfield.encoder
import jsonfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meta_translations', '0007_auto_20220520_0808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseblockdata',
            name='parsed_keys',
            field=jsonfield.fields.JSONField(blank=True, default=None, dump_kwargs={'cls': jsonfield.encoder.JSONEncoder, 'separators': (',', ':')}, load_kwargs={}),
        ),
    ]
