# Generated by Django 2.2.24 on 2022-06-08 09:08

import django.db.models.deletion
import jsonfield.encoder
import jsonfield.fields
import opaque_keys.edx.django.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('meta_translations', '0008_auto_20220520_1117'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wikitranslation',
            name='applied',
        ),
        migrations.RemoveField(
            model_name='wikitranslation',
            name='revision',
        ),
        migrations.AddField(
            model_name='courseblock',
            name='applied_translation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='wikitranslation',
            name='fetched_commits',
            field=jsonfield.fields.JSONField(blank=True, dump_kwargs={'cls': jsonfield.encoder.JSONEncoder, 'separators': (',', ':')}, load_kwargs={}, null=True),
        ),
        migrations.CreateModel(
            name='TranslationVersion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_id', opaque_keys.edx.django.models.UsageKeyField(max_length=255)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('data', jsonfield.fields.JSONField(blank=True, default={}, dump_kwargs={'cls': jsonfield.encoder.JSONEncoder, 'separators': (',', ':')}, load_kwargs={}, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='courseblock',
            name='applied_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='meta_translations.TranslationVersion'),
        ),
    ]
