# Generated by Django 2.2.24 on 2022-06-21 14:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('meta_translations', '0010_auto_20220616_1545'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetaTranslationConfiguration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_date', models.DateTimeField(auto_now_add=True, verbose_name='Change date')),
                ('enabled', models.BooleanField(default=False, verbose_name='Enabled')),
                ('staff_show_api_buttons', models.BooleanField(default=False)),
                ('normal_users_show_api_buttons', models.BooleanField(default=False)),
                ('days_settings_for_fetch_call', models.IntegerField(default=0, verbose_name='Days settings for next Fetch call')),
                ('changed_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Changed by')),
            ],
        ),
        migrations.DeleteModel(
            name='MetaApiButtonConfiguration',
        ),
    ]
