# Generated by Django 2.2.24 on 2022-06-22 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meta_translations', '0011_auto_20220621_1416'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseblock',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
