# Generated by Django 2.2.24 on 2022-06-27 12:36

import jsonfield.encoder
import jsonfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meta_translations', '0013_auto_20220627_0631'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseblock',
            name='extra',
            field=jsonfield.fields.JSONField(blank=True, default={}, dump_kwargs={'cls': jsonfield.encoder.JSONEncoder, 'separators': (',', ':')}, load_kwargs={}, null=True),
        ),
    ]
