# Generated by Django 2.2.24 on 2022-07-21 12:30

import jsonfield.encoder
import jsonfield.fields
import opaque_keys.edx.django.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meta_translations', '0014_courseblock_extra'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursetranslation',
            name='extra',
            field=jsonfield.fields.JSONField(blank=True, default={}, dump_kwargs={'cls': jsonfield.encoder.JSONEncoder, 'separators': (',', ':')}, load_kwargs={}, null=True),
        ),
        migrations.AddField(
            model_name='coursetranslation',
            name='outdated',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='coursetranslation',
            name='course_id',
            field=opaque_keys.edx.django.models.CourseKeyField(blank=True, db_index=True, max_length=255, null=True),
        ),
    ]
