# Generated by Django 2.2.24 on 2022-11-23 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meta_translations', '0015_auto_20220721_1230'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseblock',
            name='translated',
            field=models.BooleanField(default=False),
        ),
    ]
