# Generated by Django 2.2.24 on 2022-11-28 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meta_translations', '0016_courseblock_translated'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetaCronJobInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_date', models.DateTimeField(auto_now_add=True)),
                ('sent_date', models.DateTimeField(null=True)),
                ('fetched_date', models.DateTimeField(null=True)),
            ],
        ),
    ]
