# Generated by Django 3.2.13 on 2024-01-24 10:24

import jsonfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meta_translations', '0017_metacronjobinfo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='metacronjobinfo',
            options={'verbose_name': 'Cron Job Info'},
        ),
        migrations.AlterField(
            model_name='courseblock',
            name='extra',
            field=jsonfield.fields.JSONField(blank=True, default={}, null=True),
        ),
        migrations.AlterField(
            model_name='courseblock',
            name='lang',
            field=jsonfield.fields.JSONField(blank=True, default='[]'),
        ),
        migrations.AlterField(
            model_name='courseblockdata',
            name='parsed_keys',
            field=jsonfield.fields.JSONField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='coursetranslation',
            name='extra',
            field=jsonfield.fields.JSONField(blank=True, default={}, null=True),
        ),
        migrations.AlterField(
            model_name='translationversion',
            name='data',
            field=jsonfield.fields.JSONField(blank=True, default={}, null=True),
        ),
        migrations.AlterField(
            model_name='wikitranslation',
            name='fetched_commits',
            field=jsonfield.fields.JSONField(blank=True, null=True),
        ),
    ]
